
services:

  # ########
  # Database
  # ########
  point-cloud-db:
    image: mongo
    container_name: "point-cloud-db"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - "./__MONGO_DATA__:/data/db"


  # ########
  # RabbitMQ
  # ########
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s

    
  # #####################
  # Point Cloud Publisher
  # #####################
  point-cloud-publisher:
    container_name: point-cloud-publisher
    restart: on-failure
    build:
      context: ./pointCloudPublisher
      dockerfile: Dockerfile
    volumes:
      - /usr/app/node_modules
      - ./pointCloudPublisher:/usr/app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_PARTICLES_QUEUE=particles_queue
      - MONGO_DB_HOST=point-cloud-db
      - MONGO_DB_PORT=27017
      - MONGO_DB_USER=root
      - MONGO_DB_PASS=example
      - DB_NAME=point-cloud-storage
    ports:
      - 3000:3000
    depends_on:
      rabbitmq:
        condition: service_healthy
      point-cloud-db:
        condition: service_started
      

  # ####################
  # Point Cloud Ingestor
  # ####################
  point-cloud-ingestor:
    container_name: point-cloud-ingestor
    restart: on-failure
    build:
      context: ./pointCloudIngestor
      dockerfile: Dockerfile
    volumes:
      - /usr/app/node_modules
      - ./pointCloudIngestor:/usr/app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_PARTICLES_QUEUE=particles_queue
      - MONGO_DB_HOST=point-cloud-db
      - MONGO_DB_PORT=27017
      - MONGO_DB_USER=root
      - MONGO_DB_PASS=example
      - DB_NAME=point-cloud-storage
    ports:
      - 4000:4000
    depends_on:
      rabbitmq:
        condition: service_healthy
      point-cloud-db:
        condition: service_started


  # ##################
  # Point Cloud Reader
  # ##################
  point-cloud-reader:
    container_name: point-cloud-reader
    restart: on-failure
    build:
      context: ./pointCloudReader
      dockerfile: Dockerfile
    volumes:
      - /usr/app/node_modules
      - ./pointCloudReader:/usr/app
    environment:
      - MONGO_DB_HOST=point-cloud-db
      - MONGO_DB_PORT=27017
      - MONGO_DB_USER=root
      - MONGO_DB_PASS=example
      - DB_NAME=point-cloud-storage
    ports:
      - 4200:4200
    depends_on:
      point-cloud-db:
        condition: service_started
    
